name: Continuous Integration and Continuous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GitHub repository URL
        run: echo "REPOSITORY_URL=https://github.com/CauaConceicao20/ProjetoA3-pipeline" >> $GITHUB_ENV

      - name: Set NPM token
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
  build:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean package -e
        working-directory: Projeto
        
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: mvn test
        working-directory: Projeto
        
  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Install Semantic Release Changelog Plugin
        run: npm install @semantic-release/changelog

      - name: Install Semantic Release Git Plugin
        run: npm install @semantic-release/git

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        run: npx semantic-release

