name: Continuous Integration and Continuous Deployment
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  Config-ambiente:
    runs-on: windows-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GitHub repository URL
        run: echo "REPOSITORY_URL=https://github.com/CauaConceicao20/ProjetoA3-pipeline" >> $GITHUB_ENV
      
      - name: Set NPM token
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19' 
          distribution: 'adopt'

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
          
      - name: Build with Maven
        run: mvn -B clean package
        working-directory: Projeto 

      - name: Run Tests
        run: mvn test
        working-directory: Projeto 
      
      - name: Install Commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Check Commit Messages
        run: npx commitlint --from=$MAIN_COMMIT_HASH
    
      - name: Install Semantic Release Changelog Plugin
        run: npm install @semantic-release/changelog

      - name: Install Semantic Release Git Plugin
        run: npm install @semantic-release/git

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        run: npx semantic-release  
